// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("everquestlog")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/everquestlogreceiver"
)

const (
	LogsStability = component.StabilityLevelBeta
)