// Code generated by mdatagen. DO NOT EDIT.

package everquestlogreceiver

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/component/componenttest"
	"go.opentelemetry.io/collector/consumer/consumertest"
	"go.opentelemetry.io/collector/receiver/receivertest"

	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/everquestlogreceiver/internal/metadata"
)

func TestComponentLifecycle(t *testing.T) {
	factory := NewFactory()

	tests := []struct {
		name     string
		createFn func() (component.Component, error)
	}{
		{
			name: "logs-shutdown",
			createFn: func() (component.Component, error) {
				cfg := factory.CreateDefaultConfig().(*EverQuestLogConfig)
				cfg.InputConfig.Include = []string{"/tmp/test.log"}
				return factory.CreateLogs(
					context.Background(),
					receivertest.NewNopSettings(metadata.Type),
					cfg,
					consumertest.NewNop(),
				)
			},
		},
		{
			name: "logs-lifecycle",
			createFn: func() (component.Component, error) {
				cfg := factory.CreateDefaultConfig().(*EverQuestLogConfig)
				cfg.InputConfig.Include = []string{"/tmp/test.log"}
				return factory.CreateLogs(
					context.Background(),
					receivertest.NewNopSettings(metadata.Type),
					cfg,
					consumertest.NewNop(),
				)
			},
		},
	}
	
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			comp, err := tt.createFn()
			require.NoError(t, err)

			host := componenttest.NewNopHost()
			require.NoError(t, comp.Start(context.Background(), host))
			require.NoError(t, comp.Shutdown(context.Background()))
		})
	}
}

// Additional test for config loading
func TestLoadConfig(t *testing.T) {
	factory := NewFactory()
	cfg := factory.CreateDefaultConfig()

	// Test that the default config is valid
	require.NoError(t, componenttest.CheckConfigStruct(cfg))
}